#!/bin/bash

[ "$UID" -eq 0 ] || { echo "Execcute como root."; exit 1;}

read -p "Entre com o nome do Programa: " PROGRAMA

sudo apt-get purge $PROGRAMA*
sudo apt-get autoclean && sudo apt-get autoremove
